{
 "title": "IOT Project",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "TEST",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "alias": "X",
     "measurement": "helmet",
     "query": "SELECT \"accX\" FROM \"helmet\" WHERE (\"travelID\" = 512) ",
     "select": [
      [
       { "params": [ "accX" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "travelID", "operator": "=", "value": "512" }
     ]
    }
   ]
  },
  { "title": "Current Travel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "TravelID",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "travelID" ], "type": "tag" }
     ],
     "measurement": "helmet",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "helmet",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 17 },
   "format": "none",
   "targets": [
    {
     "measurement": "helmet",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "helmet",
     "select": [
      [
       { "params": [ "accX" ], "type": "field" },
       { "params": [ "1s" ], "type": "elapsed" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luminosity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "helmet",
     "query": "SELECT \"ldr\" FROM \"helmet\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ldr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Turns ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Left",
     "measurement": "turns",
     "query": "SELECT count(turn) FROM turns WHERE (turn = 'left')  GROUP BY  \"left\"",
     "select": [
      [
       { "params": [ "turn" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "turn", "operator": "=", "value": "left" }
     ]
    },
    {
     "alias": "Right",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "query": "SELECT count(turn) FROM turns WHERE (turn = 'right')  GROUP BY  \"right\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seat Status",
   "type": "graph",
   "description": "0 for \"Ορθοπεταλιά\",\n1 for normal driving",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "helmet",
     "select": [
      [
       { "params": [ "seatState" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "IMU Sensor Readings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Seat Status",
   "type": "graph",
   "description": "0 for normal driving,\n1 for \"Ορθοπεταλιά\"",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Seat",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "measurement": "helmet",
     "query": "SELECT elapsed(\"seatState\", 1s) FROM \"helmet\" WHERE (\"seatState\" = '1') AND $timeFilter",
     "select": [
      [
       { "params": [ "seatState" ], "type": "field" },
       { "params": [ "1s" ], "type": "elapsed" }
      ]
     ],
     "tags": [
      { "key": "seatState", "operator": "=", "value": "0" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Gyroscope",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "travelID" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "helmet",
     "select": [
      [
       { "params": [ "gyroX" ], "type": "field" },
       { "params": [ "X" ], "type": "alias" }
      ],
      [
       { "params": [ "gyroY" ], "type": "field" },
       { "params": [ "Y" ], "type": "alias" }
      ],
      [
       { "params": [ "gyroZ" ], "type": "field" },
       { "params": [ "Z" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accelerometer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "travelID" ], "type": "tag" }
     ],
     "measurement": "helmet",
     "select": [
      [
       { "params": [ "accX" ], "type": "field" },
       { "params": [ "X" ], "type": "alias" }
      ],
      [
       { "params": [ "accY" ], "type": "field" },
       { "params": [ "Y" ], "type": "alias" }
      ],
      [
       { "params": [ "accZ" ], "type": "field" },
       { "params": [ "Z" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Roll & Pitch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "travelID" ], "type": "tag" }
     ],
     "measurement": "helmet",
     "select": [
      [
       { "params": [ "roll" ], "type": "field" },
       { "params": [ "roll" ], "type": "alias" }
      ],
      [
       { "params": [ "pitch" ], "type": "field" },
       { "params": [ "pitch" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}